/**
 * Capture dashboard screenshots for the README.
 * Requires the dev server running (pnpm dev) with an AI provider key in .env,
 * so the AI panel renders real output.
 *
 *   pnpm dev          # in one terminal
 *   pnpm screenshots  # in another
 */
import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";

const BASE = process.env.BASE_URL || "http://localhost:3000";
const OUT = "results/screenshots";

async function main() {
  await mkdir(OUT, { recursive: true });

  // Find an at-risk project for the drill-down shot.
  const metrics = await fetch(`${BASE}/api/metrics`).then((r) => r.json());
  const atRisk =
    metrics.projects.find((p) => p.health === "at_risk") ?? metrics.projects[0];

  const browser = await chromium.launch();
  const page = await browser.newPage({
    viewport: { width: 1440, height: 900 },
    deviceScaleFactor: 2,
  });

  // Overview — wait for the live AI panel to finish generating.
  await page.goto(`${BASE}/`, { waitUntil: "networkidle" });
  await page
    .waitForFunction(() => document.body.innerText.includes("Generated by"), {
      timeout: 40000,
    })
    .catch(() => console.warn("AI panel did not finish in time; capturing anyway"));
  await page.waitForTimeout(800);
  await page.screenshot({ path: `${OUT}/overview.png`, fullPage: true });
  console.log("saved overview.png");

  // Drill-down.
  await page.goto(`${BASE}/projects/${atRisk.id}`, { waitUntil: "networkidle" });
  await page.waitForTimeout(1200);
  await page.screenshot({ path: `${OUT}/project-drilldown.png`, fullPage: true });
  console.log(`saved project-drilldown.png (${atRisk.name})`);

  // Focused AI panel shot (cropped to the AI insights card).
  await page.goto(`${BASE}/`, { waitUntil: "networkidle" });
  await page
    .waitForFunction(() => document.body.innerText.includes("Generated by"), {
      timeout: 40000,
    })
    .catch(() => {});
  await page.waitForTimeout(800);
  const aiPanel = page.locator("section", { hasText: "AI insights" }).first();
  await aiPanel.screenshot({ path: `${OUT}/ai-insights.png` });
  console.log("saved ai-insights.png");

  await browser.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
